### ISSUE TITLE
[Enhancement] - Add notification for inaccessible data

### ISSUE THREAD

**Issue by andycwilliams** [codeforpdx/PASS#694] opened 2024-11-18 08:39 UTC
### Describe the Current Behavior/Feature:

User 1 gave User 2 access to one of their documents and later revoked access to it. However, User 2 still sees that document in their list. When User 2 then tries to access it, nothing appears to happen. With no feedback they might think something is broken.

### Rationale:

There is feedback provided in the console but not for the user themselves. This is neither accessible nor user-friendly design. The user ought to be informed when something does not work as they intended it.

### Proposed Changes:

There is already a custom hook called `useNotification.js`. Import that and alert the user whenever something is no longer accessible.

**Comment by leekahung** [comment] 2024-11-18 10:10
Duplicate of Issue #595 relating to docList functionality

**Comment by omarNaifer12** [comment] 2024-11-20 12:52
Hi, I would like to work on this issue. Could you please assign it to me?

**Comment by omarNaifer12** [comment] 2024-11-20 21:04
> ### Describe the Current Behavior/Feature:
> User 1 gave User 2 access to one of their documents and later revoked access to it. However, User 2 still sees that document in their list. When User 2 then tries to access it, nothing appears to happen. With no feedback they might think something is broken.
> 
> ### Rationale:
> There is feedback provided in the console but not for the user themselves. This is neither accessible nor user-friendly design. The user ought to be informed when something does not work as they intended it.
> 
> ### Proposed Changes:
> There is already a custom hook called `useNotification.js`. Import that and alert the user whenever something is no longer accessible.

Hi, I would like to work on this issue. Could you please assign it to me?

**Closed as completed** 2024-12-03 01:07 UTC
Labels: enhancement, good first issue
