### ISSUE TITLE
Update ClientListTable to optimize for mobile view

### ISSUE THREAD

**Issue by xscottxbrownx** [codeforpdx/PASS#222] opened 2023-06-06 20:25 UTC
### Issue:

**`ClientListTable` can be better optimized for mobile view. It currently gets cut off.**

---

### Direction:

First thought is maybe to not display the `webId` column and instead have the name be a clickable link to the same URL.
And to also not display the `Last Activity` column.

<img width="1440" alt="Screenshot 2023-06-06 at 1 24 03 PM" src="https://github.com/codeforpdx/PASS/assets/71395931/aa26aabf-3313-4ec8-b3aa-063726200d8f">

<img width="501" alt="Screenshot 2023-06-06 at 1 24 12 PM" src="https://github.com/codeforpdx/PASS/assets/71395931/c8111b3b-2630-4f81-984f-ed126da60cc9">

**Comment by ogorman89** [comment] 2023-08-23 19:27
@xscottxbrownx has this already been addressed?

When I try to reproduce the list you shared above, I get a collapsed view of `ClientListTable` for all viewing dimensions. Examples below.

If that the desired behavior, we can probably close this issue. 

-or-

Do we want to display the full table for larger screen sizes but keep the collapsed view for smaller viewports? 

Ex: Iphone SE 
![Screen Shot 2023-08-23 at 12 15 09 PM](https://github.com/codeforpdx/PASS/assets/3335277/14fe0fd5-7c92-48bd-b413-110dfc235412)

Ex: Desktop
![Screen Shot 2023-08-23 at 12 15 28 PM](https://github.com/codeforpdx/PASS/assets/3335277/62433800-0642-4685-b374-4eb012168c5c)

**Comment by xscottxbrownx** [comment] 2023-08-23 20:30
> @xscottxbrownx has this already been addressed?
> 
> When I try to reproduce the list you shared above, I get a collapsed view of `ClientListTable` for all viewing dimensions. Examples below.
> 
> If that the desired behavior, we can probably close this issue.
> 
> -or-
> 
> Do we want to display the full table for larger screen sizes but keep the collapsed view for smaller viewports?

Ahhh, yes. This was an older issue, but a PR changed the fields of the table entirely which made this issue non-existent.    

And now, it seems we are trying to move away from tables entirely based on the latest designs from the UX team (Issue #343 and the latest in the Figma file that the UX team have been working on.)  Think we are heading in more of a div/container/card fashion over tables.

<img width="831" alt="Screenshot 2023-08-23 at 1 28 42 PM" src="https://github.com/codeforpdx/PASS/assets/71395931/a4cb4afd-e376-4c7c-a370-d7ae27cdd218">

But to be honest, I'm not sure if this was just mobile? I know the [figma](https://www.figma.com/file/BfsGjGbFUVvtqNq18sykoY/Pass-Project?type=design&node-id=1216-2986&mode=design&t=TMQTbWTuoVrGTdMA-0) file shows a table in desktop - but I think that was the UX team working with what we already had as dev team.

There is a UX/UI meeting tonight, maybe we can get some clarification.

**Comment by xscottxbrownx** [comment] 2023-08-23 20:33
@leekahung do you remember which PR cut out most of the table? I feel like it was one of yours somewhere.

@ogorman89 I know the document table is still there and will have the "too big for mobile" issue - but again, not sure we're moving forward with tables. So may not be worth the time until we have clarification.

**Comment by leekahung** [comment] 2023-08-23 22:29
> @leekahung do you remember which PR cut out most of the table? I feel like it was one of yours somewhere.

It was one of the PRs when we started building the Profile page and dropping the Documents page. Don't remember the specific number

**Comment by andycwilliams** [comment] 2023-09-14 02:53
I'm in contact with the UX team, figuring out the mobile layout vis-a-vis the desktop one. 

And since I'm already assigned to #343, I can also assign myself to this as well since there's a degree of overlap.

**Comment by timbot1789** [comment] 2024-02-01 01:08
Closing this in favor of improvements made in other PRs. If there's a UX team design that we want to implement, we can open a new ticket that links to the figma board.

**Closed as completed by timbot1789** 2024-02-01 01:08 UTC
Labels: refactor/optimization
